#############################################################################
# Makefile for building: verena
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 13 15:41:24 2019
# Project:  verena.pro
# Template: app
# Command: e:/prog/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile verena.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVHARMATTAN -DVHAS_MAEMO_MEEGOTOUCH_INTERFACES_DEV -D_HARMATTAN -DHARMATTAN_BOOSTER -DM_APPLICATION_NAME=\"${QMAKE_TARGET}\" -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtOpenGL -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSql -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDBus -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtWebKit -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMultimediaKit -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSystemInfo -IE:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/maemomeegotouchvideosuiteinterface -I. -Isrc -Iqmlapplicationviewer -I/usr/include/meegotouch -I/usr/include/maemo-meegotouch-interfaces -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -I/usr/X11R6/include -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,E:/usr/lib
LIBS          = $(SUBLIBS)  -LE:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -L/usr/X11R6/lib -L/usr/lib -lmeegotouchcore -lmeegotouchsettings -lmeegotouchextensions -lmaemomeegotouchvideosuiteinterface -pie -rdynamic -lmdeclarativecache -lQtSystemInfo -lQtMultimediaKit -lQtDeclarative -lQtWebKit -lQtDBus -lQtSql -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = e:/prog/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/vnetworkmanager.cpp \
		src/vvideoplayer.cpp \
		src/vdownloadmanager.cpp \
		src/vdownloadtask.cpp \
		src/vutility.cpp \
		src/vverenadatabase.cpp \
		src/vdeclarativewebview.cpp \
		src/vdeveloper.cpp \
		src/vstd.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc/moc_vdeveloper.cpp \
		moc/moc_vnetworkmanager.cpp \
		moc/moc_vvideoplayer.cpp \
		moc/moc_vdownloadmanager.cpp \
		moc/moc_vdownloadtask.cpp \
		moc/moc_vdeclarativewebview.cpp \
		moc/moc_vut.cpp \
		moc/moc_qmlapplicationviewer.cpp
OBJECTS       = obj/main.o \
		obj/vnetworkmanager.o \
		obj/vvideoplayer.o \
		obj/vdownloadmanager.o \
		obj/vdownloadtask.o \
		obj/vutility.o \
		obj/vverenadatabase.o \
		obj/vdeclarativewebview.o \
		obj/vdeveloper.o \
		obj/vstd.o \
		obj/qmlapplicationviewer.o \
		obj/moc_vdeveloper.o \
		obj/moc_vnetworkmanager.o \
		obj/moc_vvideoplayer.o \
		obj/moc_vdownloadmanager.o \
		obj/moc_vdownloadtask.o \
		obj/moc_vdeclarativewebview.o \
		obj/moc_vut.o \
		obj/moc_qmlapplicationviewer.o
DIST          = ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/videosuiteinterface-maemo-meegotouch.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		verena.pro
QMAKE_TARGET  = verena
DESTDIR       = 
TARGET        = verena

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: verena.pro  ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_defines.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_common.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/videosuiteinterface-maemo-meegotouch.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDBus.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtOpenGL.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile verena.pro
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_defines.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mgen.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_mmoc.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch_common.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/meegotouch.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/videosuiteinterface-maemo-meegotouch.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/opengl.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDBus.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtOpenGL.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
e:/prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../prog/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile verena.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/verena1.0.0 || $(MKDIR) obj/verena1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/verena1.0.0/ && $(COPY_FILE) --parents src/vdeveloper.h src/vnetworkmanager.h src/vvideoplayer.h src/vdownloadmanager.h src/vdownloadtask.h src/vverenadatabase.h src/vstd.h src/vdeclarativewebview.h src/vut.h qmlapplicationviewer/qmlapplicationviewer.h obj/verena1.0.0/ && $(COPY_FILE) --parents main.cpp src/vnetworkmanager.cpp src/vvideoplayer.cpp src/vdownloadmanager.cpp src/vdownloadtask.cpp src/vutility.cpp src/vverenadatabase.cpp src/vdeclarativewebview.cpp src/vdeveloper.cpp src/vstd.cpp qmlapplicationviewer/qmlapplicationviewer.cpp obj/verena1.0.0/ && (cd `dirname obj/verena1.0.0` && $(TAR) verena1.0.0.tar verena1.0.0 && $(COMPRESS) verena1.0.0.tar) && $(MOVE) `dirname obj/verena1.0.0`/verena1.0.0.tar.gz . && $(DEL_FILE) -r obj/verena1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_mgenerator_model_make_all:
compiler_mgenerator_model_clean:
	-$(DEL_FILE) ./gen_*
compiler_mgenerator_style_make_all:
compiler_mgenerator_style_clean:
	-$(DEL_FILE) ./gen_*
compiler_moc_header_make_all: moc/moc_vdeveloper.cpp moc/moc_vnetworkmanager.cpp moc/moc_vvideoplayer.cpp moc/moc_vdownloadmanager.cpp moc/moc_vdownloadtask.cpp moc/moc_vdeclarativewebview.cpp moc/moc_vut.cpp moc/moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_vdeveloper.cpp moc/moc_vnetworkmanager.cpp moc/moc_vvideoplayer.cpp moc/moc_vdownloadmanager.cpp moc/moc_vdownloadtask.cpp moc/moc_vdeclarativewebview.cpp moc/moc_vut.cpp moc/moc_qmlapplicationviewer.cpp
moc/moc_vdeveloper.cpp: src/vdeveloper.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vdeveloper.h -o moc/moc_vdeveloper.cpp

moc/moc_vnetworkmanager.cpp: src/vnetworkmanager.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vnetworkmanager.h -o moc/moc_vnetworkmanager.cpp

moc/moc_vvideoplayer.cpp: src/vvideoplayer.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vvideoplayer.h -o moc/moc_vvideoplayer.cpp

moc/moc_vdownloadmanager.cpp: src/vdownloadmanager.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vdownloadmanager.h -o moc/moc_vdownloadmanager.cpp

moc/moc_vdownloadtask.cpp: src/vdownloadtask.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vdownloadtask.h -o moc/moc_vdownloadtask.cpp

moc/moc_vdeclarativewebview.cpp: src/vdeclarativewebview.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vdeclarativewebview.h -o moc/moc_vdeclarativewebview.cpp

moc/moc_vut.cpp: src/vut.h
	mmoc.exe $(DEFINES) $(INCPATH) src/vut.h -o moc/moc_vut.cpp

moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	mmoc.exe $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc/moc_qmlapplicationviewer.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: main.cpp qmlapplicationviewer/qmlapplicationviewer.h \
		src/vdeveloper.h \
		src/vdeclarativewebview.h \
		src/vstd.h \
		src/vvideoplayer.h \
		src/vnetworkmanager.h \
		src/vdownloadmanager.h \
		src/vdownloadtask.h \
		src/vut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/vnetworkmanager.o: src/vnetworkmanager.cpp src/vnetworkmanager.h \
		src/vstd.h \
		src/vut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vnetworkmanager.o src/vnetworkmanager.cpp

obj/vvideoplayer.o: src/vvideoplayer.cpp src/vvideoplayer.h \
		src/vut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vvideoplayer.o src/vvideoplayer.cpp

obj/vdownloadmanager.o: src/vdownloadmanager.cpp src/vdownloadmanager.h \
		src/vnetworkmanager.h \
		src/vdownloadtask.h \
		src/vstd.h \
		src/vut.h \
		src/vverenadatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vdownloadmanager.o src/vdownloadmanager.cpp

obj/vdownloadtask.o: src/vdownloadtask.cpp src/vdownloadtask.h \
		src/vstd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vdownloadtask.o src/vdownloadtask.cpp

obj/vutility.o: src/vutility.cpp src/vut.h \
		src/vstd.h \
		src/vvideoplayer.h \
		src/vnetworkmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vutility.o src/vutility.cpp

obj/vverenadatabase.o: src/vverenadatabase.cpp src/vverenadatabase.h \
		src/vstd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vverenadatabase.o src/vverenadatabase.cpp

obj/vdeclarativewebview.o: src/vdeclarativewebview.cpp src/vdeclarativewebview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vdeclarativewebview.o src/vdeclarativewebview.cpp

obj/vdeveloper.o: src/vdeveloper.cpp src/vdeveloper.h \
		src/vstd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vdeveloper.o src/vdeveloper.cpp

obj/vstd.o: src/vstd.cpp src/vstd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vstd.o src/vstd.cpp

obj/qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

obj/moc_vdeveloper.o: moc/moc_vdeveloper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vdeveloper.o moc/moc_vdeveloper.cpp

obj/moc_vnetworkmanager.o: moc/moc_vnetworkmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vnetworkmanager.o moc/moc_vnetworkmanager.cpp

obj/moc_vvideoplayer.o: moc/moc_vvideoplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vvideoplayer.o moc/moc_vvideoplayer.cpp

obj/moc_vdownloadmanager.o: moc/moc_vdownloadmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vdownloadmanager.o moc/moc_vdownloadmanager.cpp

obj/moc_vdownloadtask.o: moc/moc_vdownloadtask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vdownloadtask.o moc/moc_vdownloadtask.cpp

obj/moc_vdeclarativewebview.o: moc/moc_vdeclarativewebview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vdeclarativewebview.o moc/moc_vdeclarativewebview.cpp

obj/moc_vut.o: moc/moc_vut.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_vut.o moc/moc_vut.cpp

obj/moc_qmlapplicationviewer.o: moc/moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qmlapplicationviewer.o moc/moc_qmlapplicationviewer.cpp

####### Install

install_splash: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/res/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/res/ 
	-$(INSTALL_FILE) e:/pro/qt/verena/res/verena_splash.png $(INSTALL_ROOT)/opt/verena/res/


uninstall_splash:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/res/verena_splash.png
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/res/ 


install_translation: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/i18n/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/i18n/ 
	-$(INSTALL_FILE) e:/pro/qt/verena/i18n/verena.zh_CN.ts $(INSTALL_ROOT)/opt/verena/i18n/
	-$(INSTALL_FILE) e:/pro/qt/verena/i18n/verena.zh_CN.qm $(INSTALL_ROOT)/opt/verena/i18n/


uninstall_translation:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/i18n/verena.zh_CN.ts 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/i18n/verena.zh_CN.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/i18n/ 


install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/qml/ 
	-$(INSTALL_DIR) e:/pro/qt/verena/qml/verena $(INSTALL_ROOT)/opt/verena/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/qml/verena
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/qml/ 


install_itemfolder_js: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/qml/ 
	-$(INSTALL_DIR) e:/pro/qt/verena/qml/js $(INSTALL_ROOT)/opt/verena/qml/


uninstall_itemfolder_js:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/qml/js
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/qml/ 


install_itemfolder_img: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/qml/ 
	-$(INSTALL_DIR) e:/pro/qt/verena/qml/image $(INSTALL_ROOT)/opt/verena/qml/


uninstall_itemfolder_img:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/verena/qml/image
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/qml/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) e:/pro/qt/verena/verena_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/verena_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/verena/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/verena/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/verena/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/verena/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/verena/bin/ 


install:  install_splash install_translation install_itemfolder_01 install_itemfolder_js install_itemfolder_img install_desktopfile install_target  FORCE

uninstall: uninstall_splash uninstall_translation uninstall_itemfolder_01 uninstall_itemfolder_js uninstall_itemfolder_img uninstall_desktopfile uninstall_target   FORCE

FORCE:

